### ISSUE TITLE
♻️ 💅 Cleanup/polish the code to automatically cascade images from the server -> server dependencies

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-docs#1082]
Copied over pending tasks from:
https://github.com/e-mission/e-mission-server/pull/961#issuecomment-2272509467

- [ ] change all the images to be stored in the emission dockerhub instead of my personal dockerhub account
   - [ ] even better, store them in github `ghcr.io` so that we don't run into issues with usage limits
- [ ] Explore whether we can stop uploading the date of of the run as an artifact since we are using an `.env` file in the dashboards. Can't this just be an output of the run?
- [ ] Also we might want to just rebuild on releases (marked with a tag) instead of every push anyway.
- [ ] and may also want to make the push conditional on the tests passing
- [ ] Instead of having two separate files for the analysis config (which then have to be kept in sync), just edit the dev in prod mode to turn off the assertions
- [ ] remove the `secret` auth method since it is unused
- [ ] consider using a similar cascade from `e-mission-common` to the various repos
   - [ ] also, consider pulling out `e-mission-core` as a separate library that is similar to `e-mission-common`
   - [ ] we will only need to pull `e-mission-core` into the dashboard repos then; we don't need the full analysis pipeline
- [ ] we currently have two copies of the cascading code (in the two dashboard repos). We should explore unifying them. Maybe nested workflows?
- [ ] Consider switching from $GITHUB_ENV to step outputs. I _think_ that the step outputs are the recommended approach to pass values from one step to another, but we should verify
- [ ] Discuss where to put in the cert configuration. We originally had it in the internal repos, then we moved it to the external repos. But now that we have one internal dockerfile per external dockerfile, maybe we can have it be internal after all. It doesn't actually hurt anything to be external, but it is unnecessary in the external repo.
- [ ] upload/store the correct tag. Right now the tag in dockerhub is of the format `<main_branch>_<date>` but the uploaded/stored tag is only the `date`, so we need to prepend the branch externally. And the branch is not always the same.

**Comment by MukuFlash03** [comment]
I have segregated the tasks into two individual groups (CI/CD, Core code) + one combo group(CI/CD + Core)

**A. CI/CD**

- [ ] 1. change all the images to be stored in the emission dockerhub instead of my personal dockerhub account
    - [ ] even better, store them in github ghcr.io so that we don't run into issues with usage limits

- [ ] 2. Explore whether we can stop uploading the date of of the run as an artifact since we are using an .env file in the dashboards. Can't this just be an output of the run?

- [ ] 3. Also we might want to just rebuild on releases (marked with a tag) instead of every push anyway. 

- [ ] 4. and may also want to make the push conditional on the tests passing

- [ ] 8. we currently have two copies of the cascading code (in the two dashboard repos). We should explore unifying them. Maybe nested workflows?

- [ ] 9. Consider switching from $GITHUB_ENV to step outputs. I think that the step outputs are the recommended approach to pass values from one step to another, but we should verify 

- [ ] 10. Discuss where to put in the cert configuration. We originally had it in the internal repos, then we moved it to the external repos. But now that we have one internal dockerfile per external dockerfile, maybe we can have it be internal after all. It doesn't actually hurt anything to be external, but it is unnecessary in the external repo.

- [ ] 11. upload/store the correct tag. Right now the tag in dockerhub is of the format <main_branch>_<date> but the uploaded/stored tag is only the date, so we need to prepend the branch externally. And the branch is not always the same.

---------

**B. Core code** 

- [ ] 5. Instead of having two separate files for the analysis config (which then have to be kept in sync), just edit the dev in prod mode to turn off the assertions

- [ ] 6. remove the secret auth method since it is unused
 
---------

**C. Core Code + CI/CD**

- [ ] 7. consider using a similar cascade from e-mission-common to the various repos
    - [ ] also, consider pulling out e-mission-core as a separate library that is similar to e-mission-common
    - [ ] we will only need to pull e-mission-core into the dashboard repos then; we don't need the full analysis pipeline

**Comment by MukuFlash03** [comment]
The order I plan to work on these:
- CI/CD: 7, 6, 2, 8, 4, 1, 3, 5
- Core: 2, 1
- Core + CI/CD: 1, 2

**Comment by MukuFlash03** [comment]
### **Task A-7: Certificates location - External or Internal?**

Fixed as a part of the redesign changes itself.

Added certificates `externally` _only in server_ repo ([commit](https://github.com/e-mission/e-mission-server/pull/976))
Only need them in images that need to connect to the AWS Document DB ([comment](https://github.nrel.gov/nrel-cloud-computing/nrelopenpath/pull/48#discussion_r39142))
- Dashboard repos are based on server image so they will have certificates.
- Node.js based images do not need them.

Since the same base server image is used by the server image dependent containers (webapp, analysis, admin-dash, public-dash-notebook), we have added it right at the source image which is the external server image. This way it is ensured that the certificates are present in all the cascading images.

**Comment by shankari** [comment]
@MukuFlash03 right we have implemented this. But I am suggesting that we revisit that decision

> Discuss where to put in the cert configuration. We originally had it in the internal repos, then we moved it to the external repos. But now that we have one internal dockerfile per external dockerfile, maybe we can have it be internal after all. It doesn't actually hurt anything to be external, but it is unnecessary in the external repo.

**Comment by MukuFlash03** [comment]
### Task A-6: Switching from $GITHUB_ENV to step outputs

Shankari's comments
> Consider switching from $GITHUB_ENV to step outputs. I think that the step outputs are the recommended approach to pass values from one step to another, but we should verify

I couldn’t find any official statement on which is the recommended approach.
But I did see [this warning](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) that says “set-output” is deprecated, switch to using environment files 

<img width="1792" alt="Screenshot 2024-09-20 at 11 49 22 AM" src="https://github.com/user-attachments/assets/f6850f9e-cefe-4fa2-821e-f94bc4abf728">


-------

Note that this doesn’t say that `“steps.output”` is deprecated; it says `“set-output”` is deprecated.
So, step outputs are still valid and we essentially have to choose between: [GITHUB_ENV](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable) and [GITHUB_OUTPUT](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-output-parameter)

---------

One argument in favor of `GITHUB_OUTPUT` is this:
- This [comment](https://github.com/orgs/community/discussions/55294#discussioncomment-5884935) mentions that Environment variables are only available in the same job. 
- Right now we do have just one job in the dashboard build workflows. 
- `GITHUB_OUTPUT` [documentation](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/passing-information-between-jobs#:~:text=Job%20outputs%20are%20available%20to%20all%20downstream%20jobs%20that%20depend%20on%20this%20job) mentions that job outputs available to all dependent downstream jobs.
- But in the future if we have more jobs, then `GITHUB_OUTPUT` could be more suited.

**Comment by MukuFlash03** [comment]
### Task A-2: Avoid uploading date as Artifacts -> Use .env file instead?

Shankari's comments
> Explore whether we can stop uploading the date of of the run as an artifact since we are using an .env file in the dashboards. Can't this just be an output of the run?

-----

REST API endpoints

I looked at some REST API endpoints to see if we can access outputs of jobs/steps in a run outside of the workflow run. 
We can then use them directly in the internal script to pull all tags.

**Not Suitable**

1. [Get a workflow run](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#get-a-workflow-run)
I did not find an API endpoint to directly reference outputs inside in a job. 
This endpoint gets details about a workflow run but does not have info on outputs.

2. [List jobs for a workflow run](https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#list-jobs-for-a-workflow-run)
This lists all jobs and steps but it only lists their completion status, time of execution and not outputs or any details.

3. [Download workflow run logs](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#download-workflow-run-logs)
I did however find an API endpoint that allows downloading workflow run logs.
This does give the outputs but it also gives everything from the logs as seen in the UI. 
This is a lot of redundant information that we will need to parse to only fetch the outputs.
It downloads logs a zip file which would again be another hassle to: `download -> extract -> read / parse -> clean up files`.

---

**Optimal Approach**

4. [Get repository content](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content)
This endpoint allows to directly read contents of a file, in our case .env files containing tags.
For instance, this [API response](https://api.github.com/repos/MukuFlash03/em-public-dashboard/contents/.env.tags?ref=cleanup-cicd) is from my forked repo where I've stored the tags in a [.env.tags](https://github.com/MukuFlash03/em-public-dashboard/blob/cleanup-cicd/.env.tags) file.
It gives the file content in `base64 encoded` format:

```
...
 "download_url": "https://raw.githubusercontent.com/MukuFlash03/em-public-dashboard/cleanup-cicd/.env.tags",
  "type": "file",
  "content": "Tk9URUJPT0tfSU1BR0VfVEFHPTIwMjQtMDktMjAtLTEzLTM2CkZST05URU5E\nX0lNQUdFX1RBRz0yMDI0LTA5LTIwLS0wNC0zOApTRVJWRVJfSU1BR0VfVEFH\nPTIwMjQtMDktMjAtLTA5LTEwCg==\n",
...
```

Decoding this base64 data (for decoding, the newline characters '\n\ need to be removed and combine the entire encoded string)
```
NOTEBOOK_IMAGE_TAG=2024-09-20--13-36
FRONTEND_IMAGE_TAG=2024-09-20--04-38
SERVER_IMAGE_TAG=2024-09-20--09-10
```

**Comment by MukuFlash03** [comment]
**Task A-2: Avoid uploading date as Artifacts -> Use .env file instead?** [Contd.]

With the API endpoint [mentioned above](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2364583414), we can directly read contents of files. 

**Proposed Approach**

To have a separate `.env.tags` file in each of the repositories: server, join-page, admin-dash, public-dash. 
This file would contain the image tag of the latest uploaded image.
In server repo: SERVER_IMAGE_TAG
In join-page repo: JOIN_IMAGE_TAG
In admin-dash repo: ADMIN_DASH_IMAGE_TAG
In public-dash: PUBLIC_DASH_NOTEBOOK_IMAGE_TAG, PUBLIC_DASH_FRONTEND_IMAGE_TAG
```

-----

**Pros of this approach**:
- Greatly reduces code in internal script to pull tags 
- - We don't have to fetch latest workflow runs as we can simply read the file contents of a file available in a public repository.
- Need only one file .env.tags in each repo that can store all image tags relevant to the repository.
- - Currently in public-dash we have two .env files (one for server tag, one for frontend tag).
- Might not need to keep track of Server image tag in the dependent dashboard repos since we will be reading the `SERVER_IMAGE_TAG` from the .env.tags file in server repo directly.
- - Can use this API endpoint in the dashboard workflows as well as internal script.
- - This would mean we would no longer have to check the separate PUSH and WORKFLOW_DISPATCH events related to server tag. For `public-dash`, still need the checks as frontend tag depends on event type.

**Comment by shankari** [comment]
why use something complicated which retrieves the file as a base64 encoded string instead of just reading the values directly using the `raw` option?

**Comment by MukuFlash03** [comment]
> why use something complicated which retrieves the file as a base64 encoded string instead of just reading the files directly using the raw option?
I just thought of sticking to using Github REST API and was looking for options within that. 
But reading the `raw` contents as text is a much better option indeed. 
It does not require any headers, authorization token for the request which is valid since it is publicly available data anyways.
Switched out the URLs and removed the base64 code.
Thank you for pointing that out!

**Comment by MukuFlash03** [comment]
### Task A-8: Stored tag format changed to <branch_name>_<timestamp> 

Currently the docker images are tagged as <branch_name>_<timestamp> but the artifact tags only had the timestamp.
The branch names are hardcoded in the internal scripts and are prefixed to the retrieved timestamps.

However, this causes a problem if the docker image upload is done from a different branch in the external GitHub workflow, since the complete returned tag in the internal script would still have the default hardcoded branch_name but latest timestamp.

Hence now storing the same tag that the docker image is tagged with including both the branch_name and timestamp.

**Comment by MukuFlash03** [comment]
First set of cleanup PRs added for **Tasks A**-[2](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2364583414), [6](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2364335425), [7](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2364315699), [8](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2369656529).

PRs: [e-mission-server](https://github.com/e-mission/e-mission-server/pull/983), [join-page](https://github.com/e-mission/nrel-openpath-join-page/pull/33), [admin-dash](https://github.com/e-mission/op-admin-dashboard/pull/132), [public-dash](https://github.com/e-mission/em-public-dashboard/pull/153)

**Comment by MukuFlash03** [comment]
### Task A-5: Unifying workflows to reduce duplicated code

Shankari's comments
> we currently have two copies of the cascading code (in the two dashboard repos). We should explore unifying them. Maybe nested workflows?

-----

Initially, I thought that only the dashboard workflows would be affected. But after the [first round](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2369780040) of changes for this cleanup issue, the `join` repo workflow is also almost identical to the dashboard repo workflows.

[Reusable workflows](https://docs.github.com/en/actions/sharing-automations/reusing-workflows) are the perfect way to achieve `DRY`.
It essentially works like a `function call` in normal programming.
For now, I'm storing the reusable workflow in the e-mission-server repo.

I have added conditional checks that check for the repo name in the reusable workflow file that determine which statements to execute depending on for which repo the workflow is running.

This is used for both push events specific to a repo as well as for the workflow dispatch events triggered on pushes to server repo.

----

**Advantages of reusable workflows**:
- No repeated code the image build process. All the other repos (join, admin-dash, public-dash) reuse the same workflow file.
- For any future changes related to GitHub actions workflow file, will no longer need to have 3 additional PRs for each repo (join, admin-dash, public-dash). Can simply modify the reusable workflow file as this is the core “function” workflow that is being called.

-----

Testing done 
Workflow runs: [Server](https://github.com/MukuFlash03/e-mission-server/actions/runs/11094904831/job/30822905097), [Join](https://github.com/MukuFlash03/nrel-openpath-join-page/actions/runs/11094937251/job/30822970008), [Admin-dash](https://github.com/MukuFlash03/op-admin-dashboard/actions/runs/11094937254/job/30822970050), [Public-dash](https://github.com/MukuFlash03/em-public-dashboard/actions/runs/11094937249/job/30822970015)

**Comment by MukuFlash03** [comment]
Highlighting some problems faced while implementing

1. Adding token to actions/checkout
Default GitHub Token is used if no token specified.
But then the "git push" command was [failing](https://github.com/MukuFlash03/e-mission-server/actions/runs/11083009200/job/30796812238) as it was unable to access files in other repos. This was because the reusable workflow is located in the server repo but it was trying to make changes to contents of other repos.
And the default GITHUB_TOKEN is [scoped to the current repository](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication), hence it does not authorize this.

Hence, I passed in the existing fine-grained token while checking out:
```
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: e-mission/${{ inputs.repo }}
          ref: ${{ inputs.branch }}
          token: ${{ secrets.GH_FG_PAT_TAGS }}
```
--------

2. 
- [Documentation](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow) says that recursive workflow calls not allowed by default 
- Stackoverflow ([link](https://stackoverflow.com/a/60418414)) - PeterEvans answer says the same
- Permissions ([link](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions))

**Comment by MukuFlash03** [comment]
### Task A-4: Run image_build_push only after tests pass successfully

Approach:
- Convert [test-with-docker](https://github.com/e-mission/e-mission-server/blob/master/.github/workflows/test-with-docker.yml) and [test-with-manual-install](https://github.com/e-mission/e-mission-server/blob/master/.github/workflows/test-with-manual-install.yml) to reusable workflows.
- Add them as jobs in image_build_push workflow.
- Build job in this workflow `needs` these test jobs as dependencies assuring that image build occurs after test jobs are successful.

-------

Test Workflow runs

- End to end run with tests, server build, dispatch: [server](https://github.com/MukuFlash03/e-mission-server/actions/runs/11096334387),  [join](https://github.com/MukuFlash03/nrel-openpath-join-page/actions/runs/11096468449), [admin-dash](https://github.com/MukuFlash03/op-admin-dashboard/actions/runs/11096468629), [public-dash](https://github.com/MukuFlash03/em-public-dashboard/actions/runs/11096468620)
- Both tests success ([run](https://github.com/MukuFlash03/e-mission-server/actions/runs/11096992880/job/30827533687))
- Docker success, Manual install failure ([run](https://github.com/MukuFlash03/e-mission-server/actions/runs/11097061776))
- Docker failure, Manual install success ([run](https://github.com/MukuFlash03/e-mission-server/actions/runs/11097075615))

-----

Details

Github actions didn't have out of the box solution for running a workflow based on results of multiple workflows where ALL workflows must have completed successfully.
We need this since both the test-with-docker and test-with-manual-install must pass.
So this needs an `AND logic.`

[workflow_run](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run) is there but this triggers the dependent workflow when either of the workflow dependencies defined as prerequisites are completed.
So this has an `OR logic`.


----

Found an alternative suggestion [here](https://stackoverflow.com/a/75597437). 
This suggests converting the pre-requisite workflows into reusable workflows.

These workflows can then be called in jobs in the workflow that needs these workflows to be run before.
Finally, these jobs can be added as dependencies for the image build job.

```
jobs:
  test-with-docker:
    uses: e-mission/e-mission-server/.github/workflows/test-with-docker.yml@master

  test-with-manual-install:
    uses: e-mission/e-mission-server/.github/workflows/test-with-manual-install.yml@master

  build:
    runs-on: ubuntu-latest
    needs: [test-with-docker, test-with-manual-install]
```

Also, removed the `push` trigger from the two `test` workflows since the `image_build_push` workflow would also be triggered on a `push` event which in its workflow triggers these two test workflows. 
Thus if not removed, each test workflow would run twice.

**Comment by MukuFlash03** [comment]
Second set of cleanup PRs added for **[Tasks](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2364289418) A**-[4](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2381837651), [5](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2381751745).

PRs: [e-mission-server](https://github.com/e-mission/e-mission-server/pull/985), [join-page](https://github.com/e-mission/nrel-openpath-join-page/pull/34), [admin-dash](https://github.com/e-mission/op-admin-dashboard/pull/136), [public-dash](https://github.com/e-mission/em-public-dashboard/pull/161)

**Comment by MukuFlash03** [comment]
### Task A-1: Switch to storing images in GHCR

This was a fairly easy switch following the [documentation](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

Will need to check the following once the first image is deployed to GHCR:
- Documentation says that default visibility for GHCR packages is private on first time push.
- If so, then for each repository, will need to go to Packages -> Package Settings -> Change Visibility (at the bottom).

**1. Changes to Dockerfile**
- Needed to add LABEL layer to ensure that the docker image is connected to the correct repository.
- For dashboard images that are dependent on the server image, changed to pull from GHCR.

**2. Workflow file**
- Login action used to login to GHCR.
- Building, Renaming, Pushing images with GHCR tag.
- Appropriate version tag names used depending on whether trigger event was release or workflow_dispatch.

**Comment by MukuFlash03** [comment]
### Task A-3: Image build/push on release instead of on every push

This was a sort of complex change since I had to handle the two different event triggers (workflow_dispatch, release) and how the version tags would need to be updated separately for each of these event types.

Converting the main image_build_push workflow to a reusable workflow was a great idea as it saved a lot of time. Else, I would have to repeat the same code and steps and checks for all the repositories.

--------

The major changes as a part of this task:

**1. Re-building on releases instead of tags**
- Earlier I had set the trigger event as tags but this would mean any time we create a new tag the workflow would be triggered.
- Instead, we are actually creating releases and not tags through the UI.
- Hence changed the trigger event to releases, specifically “published” releases.

------

**2. Both Tests and Build will happen for push events**

- Tests: We need tests to confirm everything works before merging.
- Build: Similarly, even though tests might pass, the image build could fail due to issues in Dockerfile or any files used in Dockerfile. 
- Hence to ensure that the final image that is pushed is correctly built, and we can have a correct version released, running both tests and build for push events.

------

**3. Dispatch only runs on `releases` identified by `ref_type == tag`.**

- `Dispatch` job depends on `build` job and since we now have build job running for both push and release events, dispatch job would also run for both.
- Hence restricting dispatch to run only on release events by using the ref_type check which has the value `tag` for releases and `branch` for pushes on any branch.

-----

**4. Additional version increment steps + Creating incremented version tags and releases in workflow**

- Manually creating new `release` through UI would trigger the workflows for all the repos and the new tag would be updated to the tag version set in the UI. This would be updated in the `.env` files as well.
- But for the `workflow_dispatch` as well, we need to handle creating a new tag and release for the dependent cascading images in the dashboard repositories.
- For this, I’m fetching the latest and 2nd latest server releases and checking for the type of `SemVer` release (major/minor/patch). Based on the type, similar version increment would occur for the dependent images.
- Depending on the event type (`release` / `workflow_dispatch`), either the tag created through the UI or the incremented tag version would be chosen as the new tag, respectively for each of the two trigger event types.
- This new tag is also written to the `.env` file.
- Finally, a new release is created based on this newly created tag in the workflow.

**Comment by MukuFlash03** [comment]
**B. Using GitHub REST API endpoints**

Discussions / Posts: Git tags sort [discussion](https://gist.github.com/rponte/fdc0724dd984088606b0), Github [issues](https://gist.github.com/loisaidasam/b1e6879f3deb495c22cc)

As discussed in this [comment](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2400956311), using the list of all releases API endpoint.

1. Need `jq` since we want to fetch specific `.ref` key from json response.
- Also need to handle the fact that response contains an array.
- Stackoverflow [post](https://stackoverflow.com/questions/39228500/extract-a-specific-field-from-json-output-using-jq), [post](https://superuser.com/questions/1717893/extract-element-from-json-array-with-jq)
- This [solution](https://stackoverflow.com/a/48426543) works for arrays

`$ jq -r '.[].username'`

2. Sorting tags: Blog [post](https://gastaud.io/en/article/git-sort-tags-semantic-version/), Stackoverflow [post](https://stackoverflow.com/questions/14273531/how-to-sort-git-tags-by-version-string-order-of-form-rc-x-y-z-w) 
- `$ git tag -l` :  Does an alphabetical sort. 0.2.11 will be before 0.2.2
- `$ git tag --sort=version:refname` : Solves this problem by arranging them in correct numeric order. However this gets the tags from all branches.
- `$ git tag -l | sort -V --reverse` : Sorts in reverse order.

These commands work in current repo however, whereas we want to sort the tags received from curl response from the server release tags.
- `tail` and `head` commands can be used ([post](https://stackoverflow.com/a/71076154), [post](https://www.baeldung.com/linux/head-tail-commands))

So for our case would look like:
```
tags=$(echo "$response" | jq -r '.[].tag_name')
current_server_release_tag=$(echo "$tags" | sort -V | tail -n 1)
previous_server_release_tag=$(echo "$tags" | sort -V | tail -n 2 | head -n 1)
```

**Comment by MukuFlash03** [comment]
All PRs tracker (https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2364297116)

Third set of cleanup PRs added for [Tasks](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2364289418) A - [1](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2400694386), [3](https://github.com/e-mission/e-mission-docs/issues/1082#issuecomment-2400702056)

PRs: [e-mission-server](https://github.com/e-mission/e-mission-server/pull/988), [join-page](https://github.com/e-mission/nrel-openpath-join-page/pull/35), [admin-dash](https://github.com/e-mission/op-admin-dashboard/pull/140), [public-dash](https://github.com/e-mission/em-public-dashboard/pull/165)
