### ISSUE TITLE
Demographics Survey Changes 2

### ISSUE THREAD

**Issue by sebastianbarry** [e-mission/e-mission-docs#771]
> @sebastianbarry We can either keep this issue open, or if we want to have the satisfaction of closing it, create a follow-on issue for the next round of changes
_Originally posted by @shankari in https://github.com/e-mission/e-mission-docs/issues/754#issuecomment-1212455353_

This issue is regarding any further batch of Demographics Survey Changes

### To-Do:

- [] Email Bingrong and Andy to get their input on whether or not we should keep around the "How did you usually get to your primary job last week? If you used more than one mode of transportation, please select the one used for most of the distance" question, given that OpenPATH is essentially a trip diary
- [] Determine whether or not we should keep this question in the survey, and remove it or keep it accordingly

**Comment by sebastianbarry** [comment]
### To-Do:

- [] Email Bingrong and Andy to get their input on whether or not we should keep around the "How did you usually get to your primary job last week? If you used more than one mode of transportation, please select the one used for most of the distance" question, given that OpenPATH is essentially a trip diary
- [] Determine whether or not we should keep this question in the survey, and remove it or keep it accordingly
- [] Add an additional question following "Which best describes your current job?" if the user chooses "Other", to let the user specify how they describe their current job

**Comment by sebastianbarry** [comment]
Relating to: https://github.com/e-mission/e-mission-phone/pull/868#issuecomment-1212491736

New task:

"Skip the job related questions if they say "prefer not to say". Because they already told us that they don't want to say anything about jobs, not even whether they are currently employed or not. So no need to waste their time making them go through multiple pages of job-related questions."

**Comment by sebastianbarry** [comment]
### To-Do:

- [] Email Bingrong and Andy to get their input on whether or not we should keep around the "How did you usually get to your primary job last week? If you used more than one mode of transportation, please select the one used for most of the distance" question, given that OpenPATH is essentially a trip diary
- [] Determine whether or not we should keep this question in the survey, and remove it or keep it accordingly
- [] Add an additional question following "Which best describes your current job?" if the user chooses "Other", to let the user specify how they describe their current job
- [] Skip the job related questions if they say "prefer not to say" to "Are you a paid worker?"

**Comment by sebastianbarry** [comment]
@shankari I have made the above changes and put them in PR: [https://github.com/e-mission/e-mission-phone/pull/872](https://github.com/e-mission/e-mission-phone/pull/872)
- [x] Remove primary transportation-mode related questions (they are not being used in the mode choice modeling
- [x] Add an additional question following "Which best describes your current job?" if the user chooses "Other", to let the user specify how they describe their current job
- [x] Skip the job related questions if they say "prefer not to say" to "Are you a paid worker?"

Also added spanish translations for new additions

![Simulator Screen Shot - iPhone 11 - 2022-08-12 at 13 51 37](https://user-images.githubusercontent.com/61334340/184432835-432ed4af-c19d-4fd8-a254-8e4a8cb70a13.png)
![Simulator Screen Shot - iPhone 11 - 2022-08-12 at 13 54 05](https://user-images.githubusercontent.com/61334340/184433193-e7c42a70-dec9-4e12-9fd8-66ed7fed8985.png)

**Comment by shankari** [comment]
@sebastianbarry can you please put in exactly what Bingrong/Andy said about the primary mode to work for the record?
You can then close this issue.

**Comment by sebastianbarry** [comment]
I referenced this email from your initial contact with Andy/Bingrong, where Andy said:

<img width="845" alt="image" src="https://user-images.githubusercontent.com/61334340/184561958-4e08e0fb-8f48-402f-8903-3ea960f3438b.png">

**Comment by shankari** [comment]
That is Zack, not Andy 😄

**Comment by sebastianbarry** [comment]
> That is Zack, not Andy 😄

That was a bad blunder of me I apologize 😖

I sent out another email just now checking in with Andy and Bingrong

**Comment by sebastianbarry** [comment]
Bingrong replied to my email, **confirming that we do not need this question**:

> I think it makes sense to remove that question based on your participants’ feedback. I recall we designed the survey for a location history travel pattern project which happened around the early stage of COVID, and the plan was to collect data for only a week or so and we were not sure if our participants (targeted on nrel employees at that time) went to work regularly or not within data collection period. So that question is like a bench mark for the collected data for that project. Since OpenPath now collects data from participants for longer time, their everyday travel pattern/behavior is already embedded in the data, so it makes senses to me to remove it.
Best,
Bingrong
